config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  resources :boards do
    resources :tickets do
      member do
        get :ready
        get :cancel
        get :start
        get :stop
        get :complete
        get :restart
      end
    end
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true

  has_many :tickets


end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  validates :name, presence: true, uniqueness: { :case_sensitive => false }

  belongs_to :board

  enum status: { backlog: 0, current_sprint: 1, in_progress: 2, done: 3 }


  include AASM
  aasm column: :status, enum: true do
    state :backlog, :initial => true
    state :current_sprint
    state :in_progress
    state :done

    event :ready do
      transitions from: :backlog, to: :current_sprint
    end

    event :cancel do
      transitions from: :current_sprint, to: :backlog
    end

    event :start do
      transitions from: :current_sprint, to: :in_progress
    end

    event :stop do
      transitions from: :in_progress, to: :current_sprint
    end

    event :complete do
      transitions from: :in_progress, to: :done
    end

    event :restart do
      transitions from: :done, to: :in_progress
    end
  end


  # def update_ticket_status(params)
  #   case params[:status]
  #     when 'ready'
  #       self.ready!
  #     when 'cancel'
  #       self.cancel!
  #     when 'start'
  #       self.start!
  #     when 'stop'
  #       self.stop!
  #     when 'complete'
  #       self.complete!
  #     when 'restart'
  #       self.restart!
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :destroy, :desc_tickets]

  def index
    @boards = Board.all
    @board = Board.new
    @desc_boards = @boards.sort_by(&:created_at).reverse
  end

  def show
  end

  def new
    @board = Board.new
    @tickets = @board.tickets
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to boards_path #board_path(@board)
    else
      flash.now[:errors] = @board.errors.full_messages.join(", ")
      render :new
    end
  end

  def destroy
    @board.destroy!
    redirect_to boards_path
  end

  private

  def board_params
    params.require(:board).permit(:title)
  end

  def set_board
    @board = Board.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :load_board
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def status
    @statuses = Tickets.statuses
  end

  def create
    @ticket = @board.tickets.new(ticket_params)

    if @ticket.save
      redirect_to board_path(@board) #, notice: "Ticket Created"
    else
      redirect_to board_path(@board), notice: @ticket.errors.full_messages.join(", ")
    end
  end

  def edit
  end

  def update
    if @ticket.update_attributes(ticket_params)
      redirect_to board_path(@board), notice: 'Ticket was successfully updated.'
    else
      flash.now[:errors] = @ticket.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to board_path(@board)
  end

  def ready
    set_ticket
    @ticket.ready!
    redirect_to board_path(@board) #, notice: "Ticket '#{@ticket.name}' is now in Current Sprint."
  end

  def cancel
    set_ticket
    @ticket.cancel!
    redirect_to board_path(@board) #, notice: "Ticket '#{@ticket.name}' has been cancelled."
  end

  def start
    set_ticket
    @ticket.start!
    redirect_to board_path(@board) #, notice: "Ticket '#{@ticket.name}' is now In Progress."
  end

  def stop
    set_ticket
    @ticket.stop!
    redirect_to board_path(@board) #, notice: "Ticket '#{@ticket.name}' is back in Current Sprint."
  end

  def complete
    set_ticket
    @ticket.complete!
    redirect_to board_path(@board) #, notice: "Ticket '#{@ticket.name}' is now Done."
  end

  def restart
    set_ticket
    @ticket.restart!
    redirect_to board_path(@board) #, notice: "Ticket '#{@ticket.name}' is back In Progress."
  end



  private

  def ticket_params
    params.require(:ticket).permit(:name, :description, :status)
  end

  def load_board
    @board = Board.find(params[:board_id])
  end

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/boards/_board.html.erb
<ul>
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-8">
        <h3><%= link_to title.capitalize, board_path(board) %></h3>
      </div>
      <div class="col-md-4">
        <%#= link_to "Delete", board_path(board), method: :delete %>
        <%= button_to "Delete", board_path(board), method: :delete, class: 'delete-board'  %>
      </div>

      <div class="col-md-6">
        <h4><strong>Created On: </strong> <%= board.created_at.strftime('%A %b %d, %Y') %></h4>
      </div>
    </div>
  </div>
</ul>

app/views/boards/_form.html.erb
<div class="row">
  <div class="col-md-3"></div>

  <div class="col-md-6">
    <div class="form-new-board">
      <h2 class="form-new-board-heading">Create a New Board</h2>

      <%= form_for @board, url: {action: "create"} do |f| %>
        <%#= f.label :title %>
        <%= f.text_field :title, placeholder: "Board Title", class: "form-control" %><br>

        <%= f.submit "Create Board", class: "btn btn-md btn-primary btn-block" %>
      <% end %>

    </div>
  </div>

  <div class="col-md-3"></div>
</div>

app/views/boards/_status_check.html.erb
<% if ticket.backlog? %>
  <div class="row">
    <div class="col-md-2">
      Move:
    </div>
    <div class="col-md-10 move">
      <%= link_to " Current Sprint", ready_board_ticket_path(@board, ticket) %>
    </div>
  </div>
<% elsif ticket.current_sprint? %>
  <div class="row">
    <div class="col-md-2">
      Move:
    </div>
    <div class="col-md-5 move">
      <%= link_to "Backlog", cancel_board_ticket_path(@board, ticket) %>
    </div>
    <div class="col-md-5">
      <%= link_to "In Progress", start_board_ticket_path(@board, ticket) %>
    </div>
  </div>
<% elsif ticket.in_progress? %>
  <div class="row">
    <div class="col-md-2">
      Move:
    </div>

    <div class="col-md-5 move">
      <%= link_to "Current Sprint", stop_board_ticket_path(@board, ticket) %>
    </div>

    <div class="col-md-5 done">
      <%= link_to "Done", complete_board_ticket_path(@board, ticket) %>
    </div>
  </div>
<% elsif ticket.done? %>
  <div class="row">
    <div class="col-md-2">
      Move:
    </div>

    <div class="col-md-10">
      <%= link_to "In Progress", restart_board_ticket_path(@board, ticket) %>
    </div>
  </div>
<% end %>

app/views/boards/_ticket_form.html.erb
<div class="row">
  <div class="col-md-3"></div>

  <div class="col-md-6">
    <div class="form-new-ticket">
      <h2 class="form-new-ticket-heading">Create a New Ticket</h2>

      <%= form_for [@board, Ticket.new], url: board_tickets_path(@board), method: :post do |f| %>
        <%#= f.label :name %>
        <%= f.text_field :name, placeholder: "Ticket Name", class: "form-control" %><br>

        <%#= f.label :description %>
        <%= f.text_area :description, placeholder: "Ticket Description", class: "form-control"  %><br>

        <div id="ticket-status-dropdown" >
          <%= f.label :status, "Status" %>
          <%= f.select :status, [['Backlog', :backlog],
              ['Current Sprint', :current_sprint],
              ['In Progress', :in_progress],
              ['Done', :done]] %>
        </div>
        <br>
        <br>

        <%= f.submit "Create Ticket", class: "btn btn-md btn-primary btn-block" %>
      <% end %>

    </div>
  </div>

  <div class="col-md-3"></div>
</div>

app/views/boards/index.html.erb
<div class="container">
  <div class="header cleafix">
    <h1 class="text-muted">Pivatol Hacker</h1>
    <hr>
    <div class="jumbotron">
      <%= render partial: 'form' %>
    </div>

    <div class="row existing-boards">
      <div class="col-md-12">
        <h2 class="page-title">Existing Boards</h2>
        <hr>
      </div>
      <div class="board-titles">
          <% @desc_boards.each do |board| %>
            <ul>
              <%= render partial: 'board', locals: {board: board, title: board.title} %>
            </ul>
            <hr>
          <% end %>
      </div>
    </div>

    <footer class="footer">
      <p>© whithub 2015</p>
    </footer>
  </div>
</div>

app/views/boards/new.html.erb
<%= render partial: 'form' %>

app/views/boards/show.html.erb
<div class="container">
  <div class="header">
          <h1 class="text-muted"><%= @board.title %></h1>
          <hr>
  </div>
</div>

    <div class="row waffle-board">
      <div class="col-md-3" id="backlog">
        <h3>Backlog</h3>
        <hr>
        <div class="row">
          <% @board.tickets.backlog.each do |ticket| %>
            <div class="tickets">
              <div class="row">
                <div class="col-md-4">
                  <h4 class="ticket-name"><%= ticket.name %>: </h4>
                </div>
                <div class="col-md-8 ticket-ed-links">
                  <h4>
                    <%= link_to "Edit", edit_board_ticket_path(@board, ticket) %>
                    <%= link_to "Delete", board_ticket_path(@board, ticket), method: :delete %>
                  </h4>
                </div>
              </div>

                <p>Description: <%= ticket.description %></p>

              <%= render partial: 'status_check', locals: { board: @board, ticket: ticket } %>
            </div>
            <br>
          <% end %>
        </div>
      </div>

      <div class="col-md-3" id="current_sprint">
        <h3>Current Sprint</h3>
        <hr>
        <div class="row">
          <% @board.tickets.current_sprint.each do |ticket| %>
            <div class="tickets">
              <div class="row">
                <div class="col-md-4">
                  <h4 class="ticket-name"><%= ticket.name %>: </h4>
                </div>
                <div class="col-md-8 ticket-ed-links">
                  <h4>
                    <%= link_to "Edit", edit_board_ticket_path(@board, ticket) %>
                    <%= link_to "Delete", board_ticket_path(@board, ticket), method: :delete %>
                  </h4>
                </div>
              </div>


              <p>Description: <%= ticket.description %></p>

              <%= render partial: 'status_check', locals: { board: @board, ticket: ticket } %>
            </div>
            <br>
          <% end %>
        </div>
      </div>


      <div class="col-md-3" id="in_progress">
        <h3>In Progress</h3>
        <hr>
        <div class="row">
          <% @board.tickets.in_progress.each do |ticket| %>
            <div class="tickets">
              <div class="row">
                <div class="col-md-4">
                  <h4 class="ticket-name"><%= ticket.name %>: </h4>
                </div>
                <div class="col-md-8 ticket-ed-links">
                  <h4>
                    <%= link_to "Edit", edit_board_ticket_path(@board, ticket) %>
                    <%= link_to "Delete", board_ticket_path(@board, ticket), method: :delete %>
                  </h4>
                </div>
              </div>


              <p>Description: <%= ticket.description %></p>

              <%= render partial: 'status_check', locals: { board: @board, ticket: ticket } %>
            </div>
            <br>
          <% end %>
        </div>
      </div>

      <div class="col-md-3" id="done">
        <h3>Done</h3>
        <hr>
        <div class="row">
          <% @board.tickets.done.each do |ticket| %>
            <div class="tickets">
              <div class="row">
                <div class="col-md-4">
                  <h4 class="ticket-name"><%= ticket.name %>: </h4>
                </div>
                <div class="col-md-8 ticket-ed-links">
                  <h4>
                    <%= link_to "Edit", edit_board_ticket_path(@board, ticket) %>
                    <%= link_to "Delete", board_ticket_path(@board, ticket), method: :delete %>
                  </h4>
                </div>
              </div>

              <p>Description: <%= ticket.description %></p>

              <%= render partial: 'status_check', locals: { board: @board, ticket: ticket } %>
            </div>
            <br>
          <% end %>
        </div>
      </div>
    </div>
<hr>

<div class="row">
  <div class="jumbotron" id="new-ticket-form">
    <%= render partial: 'ticket_form' %>
  </div>
</div>

<footer class="footer">
  <p>© whithub 2015</p>
</footer>

app/views/home/index.html.erb
<div class="home-page-image">
  <h1>Pivotal Hacker</h1>

  <h3><a class="btn btn-lg" href="/boards" role="button">Enter</a></h3>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="flash <%= type %>">
    <span><%= msg %></span>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PivatolHacker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!--<div id="main-container" class="container-fluid">-->
    <!--<div class="row">-->
      <%= render partial: 'layouts/flash' %>
      <!--<div class="col-md-12">-->
        <%= yield %>
      <!--</div>-->
    <!--</div>-->
  <!--</div>-->


</body>

</html>

app/views/tickets/_edit_ticket_form.html.erb
<div class="row">
  <div class="col-md-4"></div>

  <div class="col-md-4">
    <div class="form-new-ticket">
      <h2 class="form-new-ticket-heading">Edit Ticket</h2>

      <%= form_for [@board, @ticket], url: board_ticket_path(@board, @ticket), method: :put do |f| %>
        <%#= f.label :name %>
        <%= f.text_field :name, placeholder: "Ticket Name", class: "form-control" %><br>

        <%#= f.label :description %>
        <%= f.text_area :description, placeholder: "Ticket Description", class: "form-control"  %><br>

        <br>

        <%= f.submit "Update Ticket", class: "btn btn-md btn-primary btn-block" %>
      <% end %>

    </div>
  </div>

  <div class="col-md-4"></div>
</div>

app/views/tickets/_ticket_form.html.erb
<%= form_for [@board, @ticket], url: board_ticket_path(@board, @ticket), method: :put do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-field', placeholder: "Ticket Name" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-field', placeholder: "Ticket Description" %>

  <%#= f.label :status %>
  <%#= f.select :status, [['Backlog', 0], ['Current Sprint', 1], ['In Progress', 2], ['Done',3]] %>

  <%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<div class="jumbotron" id="new-ticket-form">
  <%= render partial: "edit_ticket_form" %>
</div>

app/views/tickets/show.html.erb
<div class="container">
  <div class="col-md-12 header">
    <h1 class="col-md-10 text-muted"><%= @ticket.name %></h1>

    <h3><a class="col-md-2 btn btn-sm home-page-button" href=<%= "/boards/#{@board.id}" %>, role="button" > Return to Board</a></h3>
    <!--<h3 class="col-md-2"><%= button_to "Return to Board", board_path(@board), method: :get %></h3>-->

    <hr>
  </div>
</div>

<div class="row">
  <div class="col-md-2"></div>

  <div class=" col-md-8 jumbotron">
    <div class="col-md-11">
      <h2>Description: </h2><h4><%= @ticket.description %></h4>
    </div>

    <div class="col-md-1 ticket-crud-links">
      <%= link_to "Edit", edit_board_ticket_path(@board, @ticket), class: 'btn btn-primary' %>
      <br>
      <br>
      <%= link_to "Delete", board_ticket_path(@board, @ticket), method: :delete, class: 'btn btn-primary' %>
    </div>
  </div>

  <div class="col-md-2"></div>
</div>


<div class="row">
  <hr>
  <footer class="footer">
    <p>© whithub 2015</p>
  </footer>
</div>